# Generated by Django 3.2.5 on 2022-07-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeachData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wave',
            options={'managed': False, 'ordering': ['id', '-obs_time', 'air_temp', 'water_temp', 'wind_speed', 'wind_direct', 'wave_height', 'wave_period', 'score', 'score_msg', 'beach_name']},
        ),
    ]
